from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

DEFAULT_WEIGHTS = BASE_DIR / "results" / "arcface_celeba_best.pth"
DEFAULT_FACE_LANDMARKER_MODEL = BASE_DIR / "models" / "face_landmarker.task"
ENROLL_DB_PATH = BASE_DIR / "data" / "system" / "enrollments.db"

EMBEDDING_DIM = 512
INPUT_SIZE = 112

LOW_QUALITY_UPSCALE_SIZE = 224
FACE_MIN_SOURCE_SIZE = 32
FACE_LOW_SOURCE_SIZE = 160
FACE_MIN_BLUR_SCORE = 8.0
FACE_LOW_BLUR_SCORE = 35.0
FACE_MIN_BRIGHTNESS = 35.0
FACE_MAX_BRIGHTNESS = 225.0
FACE_MIN_CONTRAST = 18.0
FACE_LOW_CONTRAST = 35.0
